
server.port: 8080
spring:
  application:
    name: task-list
  data:
      mongodb:
        uri: ${MONGODB_URI:mongodb://heroku_0nngbvrm:29bnvmu1j994a96lqmdim9pju6@ds213513.mlab.com:13513/heroku_0nngbvrm}
